server:
  port : 8086
  servlet :
      context-path: /api

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    #    url: jdbc:h2:~/jack  ---h2 url
    url: ${DB_URL:jdbc:mysql://localhost:3306/my_schema?characterEncoding=utf8&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:yan138359}
    hikari:
      connectionTestQuery: SELECT 1 FROM DUAL
      connectionTimeout: 30000
      maximumIdle : 2
      idleTimeout : 600000
      maxLifetime : 1800000
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect ---h2 dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    show-sql: true
    format_sql: true
    hibernate:
      ddl-auto: none
  mail :
    host : ${EMAIL_HOST:smtp.qq.com}
    port : ${EMAIL_PORT:465}
    username : ${EMAIL_USERNAME:466711305@qq.com}
    password : ${EMAIL_PASSWORD:tdbgxeixpdshbicd}
    from: 466711305@qq.com
    default-encoding: utf-8
    properties:
      mail:
        smtp :
          ssl:
            enable: true
          socketFactoryClass : javax.net.ssl.SSLSocketFactory
        debug : true


mybatis:
  mapper-locations: classpath:Mapper/*.xml
