server:
  port : 8080
  servlet :
      context-path: /api

girl:
  name : sally
  age : 18


spring:
  datasource:
    driverClassName: org.h2.Driver
#    url: jdbc:h2:~/test
    url: jdbc:h2:~/jack
    username: sa
    password:
    platform: h2
  h2:
    console:
      path: /h2
      enabled : true
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none

mybatis:
  mapper-locations: classpath:Mapper/*.xml
