server:
  port : 8080
  servlet :
      context-path: /api

girl:
  name : sally
  age : 18


#spring:
#  datasource:
#    driverClassName: org.h2.Driver
#    url: jdbc:h2:~/jack
#    username: sa
#    password:
#    platform: h2
#  h2:
#    console:
#      path: /h2
#      enabled : true
#      settings:
#        web-allow-others: true
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    #    url: jdbc:h2:~/jack  ---h2 url
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect ---h2 dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none

mybatis:
  mapper-locations: classpath:Mapper/*.xml
