server:
  port: 8088
  servlet:
    context-path: /demoa

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/jack
    username: sa
    password:
    platform: h2
  h2:
    console:
      path: /h2
      enabled : true
      settings:
        web-allow-others: true

  application:
    name: DemoServiceA

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always